---
name: github

on:
  push:
    branches:
      - main
  
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-reply label
        run: |
          curl --request GET \
          --url 'https://api.github.com/repos/${{ github.repository }}/releases' \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
