---
name: github

on:
  push:
    branches:
      - main

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: repos
        with:
          route: GET /repos/${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: "echo latest release: '${{ steps.repos.outputs.data }}'"
