---
name: github

on:
  push:
    branches:
      - main
  
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: setup jq  
        uses: dcarbone/install-jq-action@v1.0.1
   
      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
          
      - name: repo settings
        run: |
          curl -X PATCH \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --url 'https://api.github.com/repos/${{ github.repository }}' \
          -d '{"description":"test"}'
        env:
          SETTINGS: .github/settings.yaml
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
