---
name: github

on:
  push:
    branches:
      - main

permissions: write-all
  
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: gh edit
        run: gh repo edit --description test
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
