---
name: github

on:
  push:
    branches:
      - main

permissions: write-all
  
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: gh edit
        run: gh repo edit --description test
