---
name: Test Version

on:
  push:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          version: 1.3.9

      - name: Setup Terraform
        run: cat versions.tf

      - name: trigger provider
        run: echo https://registry.terraform.io/providers/hashicorp/azurerm/3.42.0

      - name: Setup Terraform
        run: rm -f versions.tf

      - name: Setup Terraform
        run: cat versions.tf
